name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build --build-arg VERSION=5.2 -t ghcr.io/torbencarstens/squid:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/torbencarstens/squid:${GITHUB_SHA}
